import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np

## shows point in 2d and 3d space 
def dspace():
    fig = plt.figure()
    ax = fig.add_subplot(1,2,1, projection='3d')
    ax.set_xlabel("x")
    ax.set_ylabel("z")
    ax.set_zlabel("y")
    plt.grid()
    plt.plot(5,5,5,marker = 'o')
 
    bx = fig.add_subplot(1, 2, 2)
    bx.set_xlabel('x')
    bx.set_ylabel('y')
    plt.grid()
    plt.plot(5,5, marker = 'o')
    plt.show()

## shows point in 3d wolrd coordinates
def worldC():
    fig = plt.figure()
    ax = fig.add_subplot(1,2,1, projection='3d')
    ax.set_xlabel("x")
    ax.set_ylabel("z")
    ax.set_zlabel("y")
    plt.grid()
    plt.plot(5,5,5,marker = 'o', color = 'blue')
    plt.plot(0, 0, 0, marker = 'x', color = 'red')
    plt.plot((0,3), (0,0), (0,0), color = 'red')
    plt.plot((0,0),(0,-3), (0,0), color = 'red')
    plt.plot((0,0), (0,0), (0,3), color = 'red')
    ax.text(1,0,0, 'origin')
    ax.text(0,5,6, 'P(Xw, Yw, Zw)')
    ax.set_xlim(-10,10)
    ax.set_ylim(-10,10)
    ax.set_zlim(0,10)
    plt.show()

## shows point in 3d world and camera coordinates
def camC():
    fig = plt.figure()
    ax = fig.add_subplot(1,2,1, projection='3d')
    ax.set_xlabel("x")
    ax.set_ylabel("z")
    ax.set_zlabel("y")
    plt.grid()
    plt.plot(5,5,5,marker = 'o', color = 'blue')
    plt.plot(0, 0, 0, marker = 'x', color = 'red')
    plt.plot((0,3), (0,0), (0,0), color = 'red')
    plt.plot((0,0),(0,-3), (0,0), color = 'red')
    plt.plot((0,0), (0,0), (0,3), color = 'red')
    plt.plot(15, 6, 3, marker = 'x', color = 'green')
    plt.plot((15,18), (6,6), (3,3), color = 'green')
    plt.plot((15,15),(6,3), (3,3), color = 'green')
    plt.plot((15,15), (6,6), (3,6), color = 'green')
    ax.text(1,0,0, 'origin')
    ax.text(5,5,6, '(Xc, Yc, Zc) P (Xw, Yw, Zw)')
    ax.text(16,6,3, 'camera')
    ax.set_xlim(-10,20)
    ax.set_ylim(-10,10)
    ax.set_zlim(0,10)
    plt.show()

def imgC():
    fig = plt.figure()
    ax = fig.add_subplot(1,2,1, projection='3d')
    ax.set_xlabel("x")
    ax.set_ylabel("z")
    ax.set_zlabel("y")
    plt.grid()
    plt.plot(5,5,5,marker = 'o', color = 'blue')
    plt.plot(0, 0, 0, marker = 'x', color = 'red')
    plt.plot((0,3), (0,0), (0,0), color = 'red')
    plt.plot((0,0),(0,-3), (0,0), color = 'red')
    plt.plot((0,0), (0,0), (0,3), color = 'red')
    plt.plot(15, 6, 3, marker = 'x', color = 'green')
    plt.plot((15,18), (6,6), (3,3), color = 'green')
    plt.plot((15,15),(6,3), (3,3), color = 'green')
    plt.plot((15,15), (6,6), (3,6), color = 'green')
    plt.plot((15,-10), (6,6), (3,3), color = 'black')
    points = np.array([[10, 1, -2], [10, 11, 8], [10, 11, -2], [10, 1, 8]])
    ax.scatter3D(points[0,:], points[1,:], points[2,:], points[3,:])
    ax.text(1,0,0, 'origin')
    ax.text(5,5,6, '(Xc, Yc, Zc) P (Xw, Yw, Zw)')
    ax.text(16,6,3, 'camera')
    ax.text(-10, 6, 3, 'optical axis')
    ax.set_xlim(-10,20)
    ax.set_ylim(-10,10)
    ax.set_zlim(0,10)
    plt.show()